### ISSUE TITLE
Blog dates being parsed incorrectly?

### ISSUE THREAD

**Issue by haroldtreen** [davidbalbert/blaggregator#114]
Whenever I look at Blaggregator, it's always the same articles at the top.

![image](https://cloud.githubusercontent.com/assets/1745854/19216367/a719f386-8d86-11e6-9ecc-6d11b44d2055.png)

It looks like this is happening when blogs set their date as being in the future, thus nothing current will ever pass them. 

![image](https://cloud.githubusercontent.com/assets/1745854/19216371/c65e340a-8d86-11e6-9b4d-adeb2a5c0017.png)

Could Blaggregator filter out articles that have invalid dates, so that content doesn't get stuck at the top of the feed?

Thanks :)

**Comment by punchagan** [comment]
Looks like the articles without a date aren't dealt with properly. I'll look into this. Thanks!

**Comment by punchagan** [comment]
@haroldtreen Thanks for submitting the bug report.  This has now been fixed and deployed.  The current home page will not show any changes, though, until new posts appear. 

When new posts are crawled, their date `min(post_date, current_date)`.  This way future dated posts shouldn't cause problems.  Also, the bug with posts without any date always showing up at the top has been fixed.  

To verify that the home page is fixed, make a new blog post. :wink: Thanks again!

**Comment by haroldtreen** [comment]
WOOOOO! :D

Did that same algorithm get applied to all past posts as well? Sounds like a good fix :). 

Thanks!

**Comment by punchagan** [comment]
There was only one post that needed to be fixed, and yes, that's been fixed.  I can see the homepage updating now. Thanks for the report! :+1:
